# Generated by Django 6.0.2 on 2026-02-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugMaster',
            fields=[
                ('ingredient_en', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('ingredient_kr', models.CharField(max_length=255)),
                ('item_name', models.TextField(blank=True, null=True)),
                ('efficacy', models.TextField(blank=True, null=True)),
                ('precautions', models.TextField(blank=True, null=True)),
                ('dur_data', models.JSONField(blank=True, default=dict)),
                ('source_updated_at', models.DateField(blank=True, help_text='식약처 데이터 최종 수정일', null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drug_master',
            },
        ),
        migrations.CreateModel(
            name='DurInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_en', models.CharField(db_index=True, max_length=255)),
                ('ingredient_kr', models.CharField(max_length=255)),
                ('item_name', models.CharField(db_index=True, max_length=255)),
                ('combined_ingredient', models.CharField(max_length=255)),
                ('prohibit_content', models.TextField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EYakInfo',
            fields=[
                ('item_seq', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('entp_name', models.CharField(blank=True, max_length=255)),
                ('efficacy', models.TextField(blank=True, null=True)),
                ('use_method', models.TextField(blank=True, null=True)),
                ('precautions', models.TextField(blank=True, null=True)),
                ('interaction', models.TextField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('item_image', models.URLField(blank=True, max_length=500, null=True)),
                ('source_updated_at', models.DateField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
