# Generated by Django 6.0.2 on 2026-02-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dur_type', models.CharField(db_index=True, max_length=50, verbose_name='금기유형')),
                ('ingr_code', models.CharField(db_index=True, max_length=20, verbose_name='성분코드')),
                ('ingr_eng_name', models.CharField(db_index=True, max_length=255, verbose_name='성분명(영문)')),
                ('ingr_kor_name', models.CharField(max_length=255, verbose_name='성분명(국문)')),
                ('critical_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='핵심주의값')),
                ('prohbt_content', models.TextField(blank=True, null=True, verbose_name='금기내용')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('class_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='효능군/계열')),
                ('notification_date', models.DateField(blank=True, null=True, verbose_name='공고일자')),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dur_master',
                'unique_together': {('dur_type', 'ingr_code', 'critical_value')},
            },
        ),
        migrations.DeleteModel(
            name='DrugMaster',
        ),
        migrations.DeleteModel(
            name='DurInfo',
        ),
        migrations.AlterField(
            model_name='eyakinfo',
            name='efficacy',
            field=models.TextField(blank=True, null=True, verbose_name='효능'),
        ),
        migrations.AlterField(
            model_name='eyakinfo',
            name='entp_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='업체명'),
        ),
        migrations.AlterField(
            model_name='eyakinfo',
            name='interaction',
            field=models.TextField(blank=True, null=True, verbose_name='상호작용'),
        ),
        migrations.AlterField(
            model_name='eyakinfo',
            name='item_image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='제품이미지URL'),
        ),
        migrations.AlterField(
            model_name='eyakinfo',
            name='item_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='제품명'),
        ),
        migrations.AlterField(
            model_name='eyakinfo',
            name='item_seq',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='품목기준코드'),
        ),
        migrations.AlterField(
            model_name='eyakinfo',
            name='last_synced_at',
            field=models.DateTimeField(auto_now=True, verbose_name='시스템동기화일'),
        ),
        migrations.AlterField(
            model_name='eyakinfo',
            name='precautions',
            field=models.TextField(blank=True, null=True, verbose_name='주의사항'),
        ),
        migrations.AlterField(
            model_name='eyakinfo',
            name='side_effects',
            field=models.TextField(blank=True, null=True, verbose_name='부작용'),
        ),
        migrations.AlterField(
            model_name='eyakinfo',
            name='source_updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='식약처수정일'),
        ),
        migrations.AlterField(
            model_name='eyakinfo',
            name='use_method',
            field=models.TextField(blank=True, null=True, verbose_name='사용법'),
        ),
        migrations.AlterModelTable(
            name='eyakinfo',
            table='eyak_info',
        ),
    ]
