# Generated by Django 6.0.2 on 2026-02-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_durmaster_delete_drugmaster_delete_durinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyakinfo',
            name='etc_otcc_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='전문/일반'),
        ),
    ]
