# Generated by Django 6.0.2 on 2026-02-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_eyakinfo_etc_otcc_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eyakinfo',
            options={'verbose_name': '의약품 상세 정보', 'verbose_name_plural': '의약품 상세 정보 목록'},
        ),
        migrations.AddField(
            model_name='eyakinfo',
            name='ee_doc_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='효능효과문서URL'),
        ),
        migrations.AddField(
            model_name='eyakinfo',
            name='item_eng_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='제품명(영문)'),
        ),
        migrations.AddField(
            model_name='eyakinfo',
            name='main_ingr_name',
            field=models.TextField(blank=True, null=True, verbose_name='주성분명 통합'),
        ),
        migrations.AddField(
            model_name='eyakinfo',
            name='nb_doc_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='주의사항문서URL'),
        ),
        migrations.AddField(
            model_name='eyakinfo',
            name='ud_doc_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='용법용량문서URL'),
        ),
    ]
