# Generated by Django 6.0.2 on 2026-02-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_alter_eyakinfo_options_eyakinfo_ee_doc_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyakinfo',
            name='item_eng_name',
            field=models.TextField(blank=True, null=True, verbose_name='제품명(영문)'),
        ),
        migrations.AlterField(
            model_name='eyakinfo',
            name='item_name',
            field=models.TextField(verbose_name='제품명'),
        ),
    ]
