-- Supabase (PostgreSQL) Schema for dur_master

CREATE TABLE IF NOT EXISTS public.dur_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dur_seq VARCHAR(50),
    dur_type VARCHAR(50) NOT NULL,
    type_name VARCHAR(50),
    
    ingr_code VARCHAR(20) NOT NULL,
    ingr_kor_name VARCHAR(255) NOT NULL,
    ingr_eng_name VARCHAR(255),
    
    form_name TEXT,
    mix_type VARCHAR(50),
    mix_ingr TEXT,
    ori_ingr TEXT,
    
    mixture_ingr_code VARCHAR(20),
    mixture_ingr_kor_name VARCHAR(255),
    mixture_ingr_eng_name VARCHAR(255),
    mixture_mix_type VARCHAR(50),
    mixture_class VARCHAR(255),
    mixture_ori TEXT,
    
    grade VARCHAR(50),
    max_qty VARCHAR(100),
    max_dosage_term VARCHAR(100),
    age_base VARCHAR(100),
    effect_code VARCHAR(50),
    sers_name VARCHAR(255),
    
    critical_value VARCHAR(255),
    prohbt_content TEXT,
    remark TEXT,
    class_name VARCHAR(255),
    notification_date DATE,
    del_yn VARCHAR(10) DEFAULT '정상',
    
    last_synced_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_dur_master_dur_type ON public.dur_master (dur_type);
CREATE INDEX IF NOT EXISTS idx_dur_master_ingr_code ON public.dur_master (ingr_code);
CREATE INDEX IF NOT EXISTS idx_dur_master_dur_seq ON public.dur_master (dur_seq);
